further basic developmnet, still not there yet

diff --git a/fresh b/fresh
--- a/fresh
+++ b/fresh
@@ -1,6 +1,18 @@
 #!/bin/bash
 
-usage {
+## ---------------------------------- ##
+## file naming convention assumptions ##
+## ---------------------------------- ##
+## first rule of this conenvention, underscores to be used as the seperator
+## Componets
+## - Subject ID
+## - Wave
+## - Resampling // _rs
+## leads to following structure: subjectID_resampled_wave
+## the first set of test data will not have been resampled
+## so the file name convention will be: subjectID_w1/2/3 for the time series
+
+function usage {
 	echo "Bash scripting to automate FreeSurfer usage"
 	echo "Use at your own risk, no warranty is provided"
 	echo "Flags explained"
@@ -10,10 +22,39 @@ usage {
 	echo ""
 }
 
-do_recon_all_3_tp {
+function test {
+		"$@"
+		local status=$?
+		if [ $status -ne 0 ]; then
+				echo "**** ERROR WITH: $1" >&2
+				problem=yes
+		fi
+		return $status
+}
+
+## assuming the number of cores is being dictated by a slurm allocation
+cores="$SLURM_TASKS_PER_NODE"
+
+function env_setup {
+
+	. /etc/profile.d/modules.sh
+	module purge
+	module load tcin
+
+	# stable FreeSurfer
+	if [ "$1" = "stabe" ]; then
+			module load freesurfer/6.0
+	elif [ "$1" == "dev" ]; then
+		# dev FreeSurfer
+		module load freesurfer/6-dev-20180918
+		export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=$cores
+	fi
+}
+
+function do_recon_all {
 
 	## mechanism to over write the subject id by passing a different one
-	## as the first argument to this function, if needed. 
+	## as the first argument to this function, if needed.
 	## Defaults to global otherwise.
 	if [ -z "$1" ]; then
 		local subject="$1"
@@ -22,10 +63,9 @@ do_recon_all_3_tp {
 	fi
 
 	## AFNI steps for F
-	
 
-	module purge
-	module load tcin freesurfer/6.0 
+
+	env_setup stable
 
 	## the steps that need to be carried out
 	## Needed by Erik currently
@@ -43,65 +83,47 @@ do_recon_all_3_tp {
 	recon-all -i $file3 -s $subject_$wavenumber
 		## `--> -s flag outputs to the named subject directory
 	#recon-all  -all -3T -cm -openmp 8 -T2 $directory/$subject_w1_T2_FP.nii.gz -T2pial -s $directory/$subject_w1 -hippocampal-subfields-T1T2 $directory/$subject_w1_T2_FP.nii.gz T1andT2_based -parallel -openmp 8
-	
+
 	## F's settings
 	## FIXME - placment of this var
 	## each of the following steps takes about 12 hours
 	## to run on each waves data for the subject
 	## FIXME - the -s flag's input
-	cores=12
-	recon-all -all -3T -parallel -openmp $cores -s $subject_$postpend -hippocampal-subfields-T1
-	recon-all -all -3T -parallel -openmp $cores -s $subject_$postpend -hippocampal-subfields-T1
-	recon-all -all -3T -parallel -openmp $cores -s $subject_$postpend -hippocampal-subfields-T1
 
-	## FIXME
-	## this needs to be setup properly
-	#source $envscriptsdir/freesurfer-dev-version.sh
+	for wave in 1 2 3
+	do
+		recon-all -all -3T -parallel -openmp "$cores" -s "$subject""_""$wave" -hippocampal-subfields-T1
+	done
 
-	## developmental FreeSurfer
-	
-	module purge
-	module load tcin freesurfer/6-dev-20180918
-	export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=$cores
+	env_setup dev
 
 	## FIXME - $timepoint var needs defining & is different for each
-	segmentHA_T1.sh $subject_$timepoint
-	segmentHA_T1.sh $subject_$timepoint
-	segmentHA_T1.sh $subject_$timepoint
+	segmentHA_T1.sh "$subject_$timepoint"
+	segmentHA_T1.sh "$subject_$timepoint"
+	segmentHA_T1.sh "$subject_$timepoint"
 
 	## Not needed for F
 	#segmentHA_T2.sh $subject $directory/$subject_w1_T2_FP.nii.gz T1andT2_based 1
 
 	## FIXME - $timepoint var needs defining & is different for each
-	segmentBS.sh $subject_$timepoint
-	segmentBS.sh $subject_$timepoint
-	segmentBS.sh $subject_$timepoint
+	segmentBS.sh "$subject_$timepoint"
+	segmentBS.sh "$subject_$timepoint"
+	segmentBS.sh "$subject_$timepoint"
 
 	## FIXME - $timepoint var needs defining & is different for each
-	segmentThalamicNuclei.sh $subject_$timepoint
-	segmentThalamicNuclei.sh $subject_$timepoint
-	segmentThalamicNuclei.sh $subject_$timepoint
+	segmentThalamicNuclei.sh "$subject_$timepoint"
+	segmentThalamicNuclei.sh "$subject_$timepoint"
+	segmentThalamicNuclei.sh "$subject_$timepoint"
 
-	## longitudianal
+}
 
-	module purge
-	module load tcin freesurfer/6.0 
+function do_longitudianal {
+
+	env_setup stable
 
 	## FIXME - check this variable
 	## NB NB NB
-	local subjectid=""$subhect"base"
-
-	## file naming convention assumptions
-	## first rule of this conenvention, underscores to be used as the seperator
-	## Componets
-	## Subject ID
-	## Wave
-	## Resampling // _rs
-	## leads to following structure
-	## subjectID_resampled_wave
-	## Assuming over ever 3 time series per subject
-	## the first set of test data will not have been resampled so the file name convention will be:
-	## subjectID_w1/2/3 for the time series
+	local subjectid=""$subject"base"
 
 	## FIXME
 	## NB NB
@@ -118,9 +140,7 @@ do_recon_all_3_tp {
 	#recon-all -long "$subject"_$timepoint2 "$subject"base -all
 	recon-all -long "$subject"_$timepoint3 "$subject"base -all
 
-	module purge
-	module load tcin freesurfer/6-dev-20180918
-	export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=$cores
+	env_setup dev
 
 	segmentHA_T1_long.sh "$subject"base
 
@@ -136,12 +156,10 @@ do_recon_all_3_tp {
 	## are the subject file names going to be consistent?
 	## i.e. will it always be $subject_w1_T1_FP_RS.nii.gz ??
 
-	
-
 }
 
 # get the flags
-while getopts "s:d:u" OPTION
+while getopts "s:d:f:w:nu" OPTION
 do
 	case $OPTION in
 		s)
@@ -152,9 +170,13 @@ do
 			;;
 		f)
 			file=$OPTARG
+			export $file
 			;;
-		p)
-			postpend=$OPTARG
+		w)
+			waves=(${waves[@]} "$OPTARG")
+			;;
+		n)
+			export resampled="NO"
 			;;
 		?)
 			usage
